version: '3'

services:
  app:
    image: registry.cn-shenzhen.aliyuncs.com/luler/gradio_base
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 7862:7862
    environment:
      - REPLICATE_API_KEY=
